# Xcode
- task: ArchiveFiles@2
- task: DuffleInstaller@0
  inputs:
    version: '0.1.0-ralpha.4+dramallamabuie'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
- task: AzureWebApp@1
  inputs:
    appName: 
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
